# Common
random_seed: 72

learning_rate: 0.001 # Input model's learning rate

model_type: 'Pytorch' # This value should be maintained
model:
  _target_: models.PPIBayesNet # Input your custom model
  output_size: 1 # Input your model's output size (only classification)

dataset:
    name: 'christdata' # Input your data name
    validation_split: 0.2 # Ratio of dividing train data by validation

# client
task_id: 'ppibayesian' # Input your Task Name that you register in FedOps Website

wandb: 
  use: true # Whether to use wandb
  key: ce53e10675102394f9c8ac9f89c76bcbf14ea805 # Input your wandb api key
  account: z8086486 # Input your wandb account
  project: '${dataset.name}_${task_id}'


# server
num_epochs: 20 # number of local epochs
batch_size: 64
num_rounds: 10 # Number of rounds to perform
clients_per_round: 1 # Number of clients participating in the round

server:
  strategy:
    _target_: flwr.server.strategy.FedAvg # aggregation algorithm (defalut: fedavg)
    fraction_fit: 0.00001 # because we want the number of clients to sample on each round to be solely defined by min_fit_clients
    fraction_evaluate: 0.000001 # because we want the number of clients to sample on each round to be solely defined by min_fit_clients
    min_fit_clients: ${clients_per_round} # Minimum number of clients to participate in training
    min_available_clients: ${clients_per_round} # Minimum number of clients to participate in a round
    min_evaluate_clients: ${clients_per_round} # Minimum number of clients to participate in evaluation

